"""Initial core schema: mailbox, sync, mail, attachments, audit

Revision ID: 0001_initial
Revises:
Create Date: 2026-08-27 16:32:06.486663

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Extensions.  On Cloud SQL the cloudsqlsuperuser role may create these;
    # on Supabase they are pre-installed.  pg_trgm powers fuzzy name lookups,
    # unaccent makes search ignore Slovak diacritics.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")

    # A text-search configuration that folds diacritics but does not stem.
    # PostgreSQL ships no Slovak stemmer; "simple" + unaccent is the honest
    # baseline, and semantic search (phase 3) covers what stemming would.
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_ts_config WHERE cfgname = 'sk_unaccent'
            ) THEN
                CREATE TEXT SEARCH CONFIGURATION public.sk_unaccent (COPY = simple);
                ALTER TEXT SEARCH CONFIGURATION public.sk_unaccent
                    ALTER MAPPING FOR hword, hword_part, word
                    WITH unaccent, simple;
            END IF;
        END
        $$;
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attachment_blob",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("mime_type", sa.String(length=255), nullable=True),
        sa.Column("storage_backend", sa.String(length=16), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attachment_blob")),
        sa.UniqueConstraint("sha256", name=op.f("uq_attachment_blob_sha256")),
    )
    op.create_table(
        "contact",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("primary_address", sa.String(length=320), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=True),
        sa.Column("is_own", sa.Boolean(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("message_count", sa.Integer(), nullable=False),
        sa.Column("needs_review", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact")),
        sa.UniqueConstraint("primary_address", name=op.f("uq_contact_primary_address")),
    )
    op.create_index(op.f("ix_contact_domain"), "contact", ["domain"], unique=False)
    op.create_table(
        "mailbox_account",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("google_sub", sa.String(length=64), nullable=True),
        sa.Column("oauth_refresh_token_enc", sa.Text(), nullable=True),
        sa.Column("oauth_access_token_enc", sa.Text(), nullable=True),
        sa.Column("oauth_token_expiry", sa.DateTime(timezone=True), nullable=True),
        sa.Column("oauth_scopes", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("authorised_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sync_start_date", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mailbox_account")),
        sa.UniqueConstraint("email", name=op.f("uq_mailbox_account_email")),
        sa.UniqueConstraint("google_sub", name=op.f("uq_mailbox_account_google_sub")),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor", sa.String(length=16), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=True),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column("account_id", sa.UUID(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("result", sa.String(length=16), nullable=False),
        sa.Column("automatic", sa.Boolean(), nullable=False),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["mailbox_account.id"],
            name=op.f("fk_audit_log_account_id_mailbox_account"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(
        op.f("ix_audit_log_correlation_id"), "audit_log", ["correlation_id"], unique=False
    )
    op.create_index("ix_audit_log_entity", "audit_log", ["entity_type", "entity_id"], unique=False)
    op.create_index("ix_audit_log_occurred_at", "audit_log", ["occurred_at"], unique=False)
    op.create_table(
        "contact_email",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column("address", sa.String(length=320), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contact.id"],
            name=op.f("fk_contact_email_contact_id_contact"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact_email")),
        sa.UniqueConstraint("address", name=op.f("uq_contact_email_address")),
    )
    op.create_index(
        op.f("ix_contact_email_contact_id"), "contact_email", ["contact_id"], unique=False
    )
    op.create_table(
        "email_thread",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("gmail_thread_id", sa.String(length=64), nullable=False),
        sa.Column("subject", sa.Text(), nullable=True),
        sa.Column("snippet", sa.Text(), nullable=True),
        sa.Column("message_count", sa.Integer(), nullable=False),
        sa.Column("first_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_message_direction", sa.String(length=16), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["mailbox_account.id"],
            name=op.f("fk_email_thread_account_id_mailbox_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_thread")),
        sa.UniqueConstraint(
            "account_id", "gmail_thread_id", name="uq_email_thread_account_gmail_id"
        ),
    )
    op.create_index(
        "ix_email_thread_last_message_at",
        "email_thread",
        ["account_id", "last_message_at"],
        unique=False,
    )
    op.create_table(
        "mailbox_address",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("address", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["mailbox_account.id"],
            name=op.f("fk_mailbox_address_account_id_mailbox_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mailbox_address")),
        sa.UniqueConstraint("account_id", "address", name="uq_mailbox_address_account_address"),
    )
    op.create_index(
        op.f("ix_mailbox_address_account_id"), "mailbox_address", ["account_id"], unique=False
    )
    op.create_index("ix_mailbox_address_address", "mailbox_address", ["address"], unique=False)
    op.create_table(
        "sync_run",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("messages_seen", sa.Integer(), nullable=False),
        sa.Column("messages_created", sa.Integer(), nullable=False),
        sa.Column("messages_updated", sa.Integer(), nullable=False),
        sa.Column("messages_skipped", sa.Integer(), nullable=False),
        sa.Column("threads_touched", sa.Integer(), nullable=False),
        sa.Column("attachments_created", sa.Integer(), nullable=False),
        sa.Column("start_history_id", sa.BigInteger(), nullable=True),
        sa.Column("end_history_id", sa.BigInteger(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["mailbox_account.id"],
            name=op.f("fk_sync_run_account_id_mailbox_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_run")),
    )
    op.create_index(
        "ix_sync_run_account_started", "sync_run", ["account_id", "started_at"], unique=False
    )
    op.create_table(
        "sync_state",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("last_history_id", sa.BigInteger(), nullable=True),
        sa.Column("initial_sync_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("initial_sync_page_token", sa.Text(), nullable=True),
        sa.Column("total_messages_synced", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["mailbox_account.id"],
            name=op.f("fk_sync_state_account_id_mailbox_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_state")),
        sa.UniqueConstraint("account_id", name=op.f("uq_sync_state_account_id")),
    )
    op.create_table(
        "email_message",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("gmail_message_id", sa.String(length=64), nullable=False),
        sa.Column("gmail_thread_id", sa.String(length=64), nullable=False),
        sa.Column("history_id", sa.BigInteger(), nullable=True),
        sa.Column("rfc822_message_id", sa.Text(), nullable=True),
        sa.Column("in_reply_to", sa.Text(), nullable=True),
        sa.Column("references", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("subject", sa.Text(), nullable=True),
        sa.Column("from_address", sa.String(length=320), nullable=True),
        sa.Column("from_name", sa.String(length=255), nullable=True),
        sa.Column("account_address", sa.String(length=320), nullable=True),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("internal_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("body_text", sa.Text(), nullable=True),
        sa.Column("body_html", sa.Text(), nullable=True),
        sa.Column("snippet", sa.Text(), nullable=True),
        sa.Column("labels", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("size_estimate", sa.Integer(), nullable=True),
        sa.Column("has_attachments", sa.Boolean(), nullable=False),
        sa.Column("raw_headers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "direction IN ('inbound','outbound','internal','unknown')",
            name=op.f("ck_email_message_direction_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["mailbox_account.id"],
            name=op.f("fk_email_message_account_id_mailbox_account"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["email_thread.id"],
            name=op.f("fk_email_message_thread_id_email_thread"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_message")),
        sa.UniqueConstraint(
            "account_id", "gmail_message_id", name="uq_email_message_account_gmail_id"
        ),
    )
    op.create_index(
        op.f("ix_email_message_account_address"), "email_message", ["account_address"], unique=False
    )
    op.create_index(
        "ix_email_message_from_address", "email_message", ["from_address"], unique=False
    )
    op.create_index("ix_email_message_rfc822", "email_message", ["rfc822_message_id"], unique=False)
    op.create_index(
        "ix_email_message_sent_at", "email_message", ["account_id", "sent_at"], unique=False
    )
    op.create_index(
        "ix_email_message_thread", "email_message", ["thread_id", "sent_at"], unique=False
    )
    op.create_table(
        "attachment",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("blob_id", sa.UUID(), nullable=True),
        sa.Column("part_id", sa.String(length=32), nullable=False),
        sa.Column("gmail_attachment_id", sa.Text(), nullable=True),
        sa.Column("filename", sa.Text(), nullable=True),
        sa.Column("mime_type", sa.String(length=255), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("content_id", sa.Text(), nullable=True),
        sa.Column("is_inline", sa.Boolean(), nullable=False),
        sa.Column("download_status", sa.String(length=24), nullable=False),
        sa.Column("download_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["mailbox_account.id"],
            name=op.f("fk_attachment_account_id_mailbox_account"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["blob_id"],
            ["attachment_blob.id"],
            name=op.f("fk_attachment_blob_id_attachment_blob"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["email_message.id"],
            name=op.f("fk_attachment_message_id_email_message"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attachment")),
        sa.UniqueConstraint("message_id", "part_id", name="uq_attachment_message_part"),
    )
    op.create_index("ix_attachment_blob", "attachment", ["blob_id"], unique=False)
    op.create_index("ix_attachment_filename", "attachment", ["filename"], unique=False)
    op.create_table(
        "email_participant",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("address", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_own", sa.Boolean(), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "kind IN ('from','to','cc','bcc','reply_to','delivered_to')",
            name=op.f("ck_email_participant_kind_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contact.id"],
            name=op.f("fk_email_participant_contact_id_contact"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["email_message.id"],
            name=op.f("fk_email_participant_message_id_email_message"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_participant")),
    )
    op.create_index("ix_email_participant_address", "email_participant", ["address"], unique=False)
    op.create_index(
        op.f("ix_email_participant_contact_id"), "email_participant", ["contact_id"], unique=False
    )
    op.create_index(
        "ix_email_participant_message_kind",
        "email_participant",
        ["message_id", "kind"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Full-text search column, maintained by PostgreSQL itself so it can never
    # drift from the row it describes.  Subject is weighted above body.
    op.execute(
        """
        ALTER TABLE email_message
        ADD COLUMN search_vector tsvector
        GENERATED ALWAYS AS (
            setweight(to_tsvector('public.sk_unaccent', coalesce(subject, '')), 'A')
            || setweight(to_tsvector('public.sk_unaccent', coalesce(from_address, '')), 'B')
            || setweight(to_tsvector('public.sk_unaccent', coalesce(body_text, '')), 'C')
        ) STORED
        """
    )
    op.execute("CREATE INDEX ix_email_message_search ON email_message USING GIN (search_vector)")
    op.execute("CREATE INDEX ix_email_message_labels ON email_message USING GIN (labels)")
    op.execute("CREATE INDEX ix_contact_name_trgm ON contact USING GIN (display_name gin_trgm_ops)")
    op.execute(
        "CREATE INDEX ix_email_thread_subject_trgm ON email_thread USING GIN (subject gin_trgm_ops)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_email_thread_subject_trgm")
    op.execute("DROP INDEX IF EXISTS ix_contact_name_trgm")
    op.execute("DROP INDEX IF EXISTS ix_email_message_labels")
    op.execute("DROP INDEX IF EXISTS ix_email_message_search")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_email_participant_message_kind", table_name="email_participant")
    op.drop_index(op.f("ix_email_participant_contact_id"), table_name="email_participant")
    op.drop_index("ix_email_participant_address", table_name="email_participant")
    op.drop_table("email_participant")
    op.drop_index("ix_attachment_filename", table_name="attachment")
    op.drop_index("ix_attachment_blob", table_name="attachment")
    op.drop_table("attachment")
    op.drop_index("ix_email_message_thread", table_name="email_message")
    op.drop_index("ix_email_message_sent_at", table_name="email_message")
    op.drop_index("ix_email_message_rfc822", table_name="email_message")
    op.drop_index("ix_email_message_from_address", table_name="email_message")
    op.drop_index(op.f("ix_email_message_account_address"), table_name="email_message")
    op.drop_table("email_message")
    op.drop_table("sync_state")
    op.drop_index("ix_sync_run_account_started", table_name="sync_run")
    op.drop_table("sync_run")
    op.drop_index("ix_mailbox_address_address", table_name="mailbox_address")
    op.drop_index(op.f("ix_mailbox_address_account_id"), table_name="mailbox_address")
    op.drop_table("mailbox_address")
    op.drop_index("ix_email_thread_last_message_at", table_name="email_thread")
    op.drop_table("email_thread")
    op.drop_index(op.f("ix_contact_email_contact_id"), table_name="contact_email")
    op.drop_table("contact_email")
    op.drop_index("ix_audit_log_occurred_at", table_name="audit_log")
    op.drop_index("ix_audit_log_entity", table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_correlation_id"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_table("mailbox_account")
    op.drop_index(op.f("ix_contact_domain"), table_name="contact")
    op.drop_table("contact")
    op.drop_table("attachment_blob")
    # ### end Alembic commands ###
    op.execute("DROP TEXT SEARCH CONFIGURATION IF EXISTS public.sk_unaccent")
