"""document text extraction

Revision ID: 0003_documents
Revises: 0002_access
Create Date: 2026-08-28 07:10:42.481902

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0003_documents"
down_revision: str | None = "0002_access"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_text",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("blob_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("method", sa.String(length=32), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("char_count", sa.Integer(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("truncated", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("extracted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('extracted','empty','needs_ocr','unsupported','failed')",
            name=op.f("ck_document_text_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["blob_id"],
            ["attachment_blob.id"],
            name=op.f("fk_document_text_blob_id_attachment_blob"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_text")),
        sa.UniqueConstraint("blob_id", name=op.f("uq_document_text_blob_id")),
    )
    op.create_index(op.f("ix_document_text_status"), "document_text", ["status"], unique=False)
    # Same expression as DOCUMENT_SEARCH_VECTOR_EXPRESSION in app/db/models.py.
    op.execute(
        """
        ALTER TABLE document_text
        ADD COLUMN search_vector tsvector
        GENERATED ALWAYS AS (
            to_tsvector('public.sk_unaccent', coalesce(text, ''))
        ) STORED
        """
    )
    op.execute("CREATE INDEX ix_document_text_search ON document_text USING GIN (search_vector)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # Dropping the table removes its indexes and the generated column with it.
    op.drop_table("document_text")
