"""clients and matters

Revision ID: 0004_matters
Revises: 0003_documents
Create Date: 2026-08-28 07:19:04.948364

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0004_matters"
down_revision: str | None = "0003_documents"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("registration_number", sa.String(length=32), nullable=True),
        sa.Column("domains", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company")),
    )
    op.create_index(
        "ix_company_name_trgm",
        "company",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index(
        op.f("ix_company_registration_number"), "company", ["registration_number"], unique=False
    )
    op.create_table(
        "client",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("reference", sa.String(length=64), nullable=True),
        sa.Column("company_id", sa.UUID(), nullable=True),
        sa.Column("contact_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("retention_note", sa.Text(), nullable=True),
        sa.Column("retention_until", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active','inactive','archived')", name=op.f("ck_client_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.id"],
            name=op.f("fk_client_company_id_company"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contact.id"],
            name=op.f("fk_client_contact_id_contact"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_client")),
        sa.UniqueConstraint("reference", name=op.f("uq_client_reference")),
    )
    op.create_index(op.f("ix_client_company_id"), "client", ["company_id"], unique=False)
    op.create_index(op.f("ix_client_contact_id"), "client", ["contact_id"], unique=False)
    op.create_index(
        "ix_client_name_trgm",
        "client",
        ["display_name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"display_name": "gin_trgm_ops"},
    )
    op.create_table(
        "matter",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("reference", sa.String(length=64), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("opened_on", sa.Date(), nullable=True),
        sa.Column("closed_on", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('open','pending','closed')", name=op.f("ck_matter_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client.id"],
            name=op.f("fk_matter_client_id_client"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_matter")),
        sa.UniqueConstraint("client_id", "reference", name="uq_matter_client_reference"),
    )
    op.create_index("ix_matter_client_status", "matter", ["client_id", "status"], unique=False)
    op.create_index(
        "ix_matter_title_trgm",
        "matter",
        ["title"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    op.create_table(
        "matter_link",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("matter_id", sa.UUID(), nullable=False),
        sa.Column("target_type", sa.String(length=16), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("method", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("needs_review", sa.Boolean(), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "target_type IN ('thread','message','attachment','contact')",
            name=op.f("ck_matter_link_target_type_valid"),
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_matter_link_confidence_in_range")
        ),
        sa.ForeignKeyConstraint(
            ["matter_id"],
            ["matter.id"],
            name=op.f("fk_matter_link_matter_id_matter"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_matter_link")),
        sa.UniqueConstraint("matter_id", "target_type", "target_id", name="uq_matter_link_target"),
    )
    op.create_index("ix_matter_link_review", "matter_link", ["needs_review"], unique=False)
    op.create_index(
        "ix_matter_link_target", "matter_link", ["target_type", "target_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_matter_link_target", table_name="matter_link")
    op.drop_index("ix_matter_link_review", table_name="matter_link")
    op.drop_table("matter_link")
    op.drop_index(
        "ix_matter_title_trgm",
        table_name="matter",
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    op.drop_index("ix_matter_client_status", table_name="matter")
    op.drop_table("matter")
    op.drop_index(
        "ix_client_name_trgm",
        table_name="client",
        postgresql_using="gin",
        postgresql_ops={"display_name": "gin_trgm_ops"},
    )
    op.drop_index(op.f("ix_client_contact_id"), table_name="client")
    op.drop_index(op.f("ix_client_company_id"), table_name="client")
    op.drop_table("client")
    op.drop_index(op.f("ix_company_registration_number"), table_name="company")
    op.drop_index(
        "ix_company_name_trgm",
        table_name="company",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_table("company")
    # ### end Alembic commands ###
