"""docx revisions and comments

Revision ID: 0005_revisions
Revises: 0004_matters
Create Date: 2026-08-28 07:38:07.688839

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0005_revisions"
down_revision: str | None = "0004_matters"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("document_text", sa.Column("deleted_text", sa.Text(), nullable=True))
    op.add_column("document_text", sa.Column("comment_text", sa.Text(), nullable=True))
    op.add_column(
        "document_text",
        sa.Column("revision_count", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "document_text", sa.Column("revision_authors", postgresql.ARRAY(sa.Text()), nullable=True)
    )
    op.add_column("document_text", sa.Column("revision_summary", sa.Text(), nullable=True))
    # The search vector must now also cover margin comments, which carry the
    # substance of a negotiation.  A generated column cannot be altered in
    # place, so it is dropped and rebuilt — Alembic cannot autogenerate this,
    # because it does not compare computed expressions.
    op.execute("DROP INDEX IF EXISTS ix_document_text_search")
    op.execute("ALTER TABLE document_text DROP COLUMN IF EXISTS search_vector")
    op.execute(
        """
        ALTER TABLE document_text
        ADD COLUMN search_vector tsvector
        GENERATED ALWAYS AS (
            to_tsvector(
                'public.sk_unaccent',
                coalesce(text, '') || ' ' || coalesce(comment_text, '')
            )
        ) STORED
        """
    )
    op.execute("CREATE INDEX ix_document_text_search ON document_text USING GIN (search_vector)")
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_document_text_search")
    op.execute("ALTER TABLE document_text DROP COLUMN IF EXISTS search_vector")
    op.execute(
        """
        ALTER TABLE document_text
        ADD COLUMN search_vector tsvector
        GENERATED ALWAYS AS (
            to_tsvector('public.sk_unaccent', coalesce(text, ''))
        ) STORED
        """
    )
    op.execute("CREATE INDEX ix_document_text_search ON document_text USING GIN (search_vector)")
    op.drop_column("document_text", "revision_summary")
    op.drop_column("document_text", "revision_authors")
    op.drop_column("document_text", "revision_count")
    op.drop_column("document_text", "comment_text")
    op.drop_column("document_text", "deleted_text")
