"""pending actions

Revision ID: 0006_actions
Revises: 0005_revisions
Create Date: 2026-08-28 12:01:16.423988

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0006_actions"
down_revision: str | None = "0005_revisions"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pending_action",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("action_type", sa.String(length=32), nullable=False),
        sa.Column("risk_tier", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("target_type", sa.String(length=16), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=True),
        sa.Column("gmail_target_id", sa.String(length=64), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("requested_by", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_by", sa.String(length=64), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("undo_hint", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "risk_tier IN ('automatic','configurable','approval')",
            name=op.f("ck_pending_action_risk_tier_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('pending','approved','rejected','executed','failed','expired')",
            name=op.f("ck_pending_action_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["mailbox_account.id"],
            name=op.f("fk_pending_action_account_id_mailbox_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pending_action")),
    )
    op.create_index(
        "ix_pending_action_status", "pending_action", ["status", "created_at"], unique=False
    )
    op.create_index(
        "ix_pending_action_target", "pending_action", ["target_type", "target_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_pending_action_target", table_name="pending_action")
    op.drop_index("ix_pending_action_status", table_name="pending_action")
    op.drop_table("pending_action")
    # ### end Alembic commands ###
