"""pkce code verifier on oauth state

Revision ID: 0007_pkce
Revises: 0006_actions
Create Date: 2026-08-28 12:59:54.354014

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0007_pkce"
down_revision: str | None = "0006_actions"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("oauth_state", sa.Column("code_verifier", sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("oauth_state", "code_verifier")
    # ### end Alembic commands ###
