"""filing folders

Where documents for one of my own companies go on Drive.  Filing is by the
entity that was billed, not by who sent the invoice.

Revision ID: e5c2d14e2959
Revises: 0009_notdoc
Create Date: 2026-08-31 14:12:58.493304

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0010_filing"
down_revision: str | None = "0009_notdoc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "filing_folder",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("drive_folder_id", sa.String(length=128), nullable=False),
        sa.Column("match_terms", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_filing_folder")),
        sa.UniqueConstraint("name", name="uq_filing_folder_name"),
    )
    op.create_index("ix_filing_folder_active", "filing_folder", ["is_active"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_filing_folder_active", table_name="filing_folder")
    op.drop_table("filing_folder")
    # ### end Alembic commands ###
